//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerceDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EcommerceDBEntities : DbContext
    {
        public EcommerceDBEntities()
            : base("name=EcommerceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Products1> Products1 { get; set; }
    
        public virtual int orderDetails(Nullable<int> p_id, Nullable<int> p_prodId)
        {
            var p_idParameter = p_id.HasValue ?
                new ObjectParameter("p_id", p_id) :
                new ObjectParameter("p_id", typeof(int));
    
            var p_prodIdParameter = p_prodId.HasValue ?
                new ObjectParameter("p_prodId", p_prodId) :
                new ObjectParameter("p_prodId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("orderDetails", p_idParameter, p_prodIdParameter);
        }
    }
}
