//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerceDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int Orders_Id { get; set; }
        public int Products1_prodId { get; set; }
    
        public virtual Products1 Products1 { get; set; }
    }
}
